Training/Controllers/BukuController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Training.Data.Entity;
using Training.API.Service;

namespace Training.Controllers
{
    [Authorize]
    public class BukuController : Controller
    {
        public IActionResult IndexBukus()
        {
            return View();
        }

        public IActionResult DetailsBuku()
        {
            return View();
        }

        public IActionResult TambahBuku()
        {
            return View();
        }

        public IActionResult DeleteBuku()
        {
            return View();
        }

        public IActionResult EditBuku()
        { 
            return View();
        }

        public IActionResult DaftarPeminjam()
        {
            return View();
        }

        public IActionResult DetailPeminjaman()
        {
            return View();
        }
    }
}

Training/Views/Buku/DaftarPeminjam.cshtml
@model IEnumerable<Training.Core.Model.PeminjamanVM>
@{
    ViewBag.Title = " Daftar Peminjam Buku";
}

<h2> Daftar Peminjam Buku </h2>

@if (Model != null && Model.Any())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-md-12">
            <table id="tableOrder" class="table table-hover">
                <tr>

                    <th>Nama Peminjam</th>
                    <th>Tanggal Peminjam</th>
                    <th>Tanggal Kembali</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
                @foreach (var pinjam in Model)
                {
                    <tr>

                        <td>@pinjam.Peminjam</td>
                        <td>@pinjam.OrderDate</td>
                        <td>@pinjam.ReturnDate</td>
                        <td>@pinjam.Status</td>
                        <td>@Html.ActionLink("Detail", "DetailPeminjaman", "Buku", new { id = pinjam.OrderId }, null)</td>
                    </tr>
                }
            </table>
        </div>
    </div>
}

else if (string.IsNullOrEmpty(ViewBag.Success))
{
    <div class="alert alert-warning" role="alert"> Daftar peminjaman buku tidak ada.</div>
}
else if (ViewBag.Success == "Error")
{
    <div class="alert alert-danger" role="alert"> Tidak dapat menampilkan daftar peminjaman buku. Silahkan hubungi Admin.</div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
}

Training/Views/Buku/DeleteBuku.cshtml
@model Training.Core.Model.Buku

@{
    ViewBag.Title = " Hapus Buku";
}

<h2> Hapus Buku</h2>

<h4> Apa kamu yakin ingin menghapus buku ini? </h4>

<div>
    <dl class="dl-horizontal">
        <dt> Nama Kategori </dt>
        <dd> @Html.DisplayFor(model => model.Kategori.NamaKategori) </dd>

        <dt> Judul Buku </dt>
        <dd> @Html.DisplayFor(model => model.Judul) </dd>

        <dt> Nama Penulis </dt>
        <dd> @Html.DisplayFor(model => model.Penulis) </dd>

        <dt> Nama Penerbit </dt>
        <dd> @Html.DisplayFor(model => model.Penerbit) </dd>

        <dt> Deskripsi </dt>
        <dd> @Html.DisplayFor(model => model.Deskripsi) </dd>

        <dt> Status Buku</dt>
        <dd> @Html.DisplayFor(model => model.Status) </dd>

        <dt> Gambar Buku </dt>
        <dd> @Html.DisplayFor(model => model.Gambar) </dd>
    </dl>

    <div class="form-group">
        <label class="col-md-2 control-label" for="submit"></label>
        <div class="col-md-10">
            <button id="submit" name="submit" type="submit" class="btn btn-danger"> Delete </button>
        </div>
    </div>

    <div>
        <a href="/Buku">Back to List</a>
    </div>
</div>

Training/Views/Buku/DetailPeminjaman.cshtml
@using Training.API.Service.Home
@model IEnumerable<Training.Core.Model.PeminjamanDetailVM>
@{
    ViewBag.Title = " Detail Peminjaman ";
}

<h2> Detail Peminjaman </h2>

@if (Model != null && Model.Any())
{
    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-12">
                <table id="tableOrder" class="table table-hover">
                    <tr>
                        <th></th>
                        <th>Penulis</th>
                        <th>Judul Buku</th>
                    </tr>
                    @foreach (var buku in Model)
                    {
                        <tr>
                            <td>
                                <img style="width:58px;height:60px" src="@buku.Gambar"/>
                            </td>
                            <td>@buku.Penulis</td>
                            <td>@buku.Judul</td>

                        </tr>
                    }
                </table>
            </div>
        </div>
        <div class="modal-footer">
            <button type="submit" name="answer" value="Cancel" class="btn btn-secondary">Cancel</button>
            @if (!Model.FirstOrDefault().Status)
            {
                <button type="submit" name="answer" value="Save" class="btn btn-primary">Kembalikan Buku</button>
            }

        </div>
    }

}
else if (string.IsNullOrEmpty(ViewBag.Success))
{
    <div class="alert alert-warning" role="alert"> Tidak ada data.</div>
}
else if (ViewBag.Success == "Error")
{
    <div class="alert alert-danger" role="alert"> Tidak dapat menyimpan. Silahkan hubungi Admin.</div>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
}
else if (ViewBag.Success == "Success")
{
    <div class="alert alert-success" role="alert">Berhasil.</div>

}

Training/Views/Buku/DetailsBuku.cshtml
@model Training.Core.Model.Buku

@{
    ViewBag.Title = "Details Buku";
}

<h2> Details Buku</h2>

<div>
    <dl class="dl-horizontal">
        <dt> Nama Kategori </dt>
        <dd> @Html.DisplayFor(model => model.Kategori.NamaKategori) </dd>

        <dt> Judul Buku </dt>
        <dd> @Html.DisplayFor(model => model.Judul) </dd>

        <dt> Nama Penulis </dt>
        <dd> @Html.DisplayFor(model => model.Penulis) </dd>

        <dt> Nama Penerbit </dt>
        <dd> @Html.DisplayFor(model => model.Penerbit) </dd>

        <dt> Deskripsi </dt>
        <dd> @Html.DisplayFor(model => model.Deskripsi) </dd>

        <dt> Status Buku</dt>
        <dd> @Html.DisplayFor(model => model.Status) </dd>

        <dt> Gambar Buku </dt>
        <dd> @Html.DisplayFor(model => model.Gambar) </dd>
    </dl>
</div>

<div>
    <a href="/Buku/EditBuku/@Model.BukuId">Edit</a>
    <a href="/Buku">Back to List</a>
</div>

Training/Views/Buku/EditBuku.cshtml
@model Training.Core.Model.Buku

@{
    ViewBag.Title = "Edit Buku";
}

<h2> Edit Buku </h2>

<div class="container>
    <div class="row">
        <form class="form-horizontal">
            <fieldset>
                <legend>
                    Edit Buku
                </legend>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="Judul"> Judul Buku </label>
                    <div class="col-md-10">
                        <input id="Judul" name="Judul" type="text" placeholder="" class="form-control input-md" required="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="Penulis">Nama Penulis</label>
                    <div class="col-md-10">
                        <input id="penulis" name="Penulis" type="text" placeholder="" class="form-control input-md" required="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="Role">Nama Penerbit</label>
                    <div class="col-md-10">
                        <input id="penerbit" name="Penerbit" type="text" placeholder="" class="form-control input-md" required="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="Role">Deskripsi</label>
                    <div class="col-md-10">
                        <input id="Deskripsi" name="Deskripsi" type="text" placeholder="" class="form-control input-md" required="">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="KategoriId">Kategori</label>
                    <div class="col-md-10">
                        <input id="KategoriId" name="KategoriId" type="text" placeholder="" class="form-control input-md" required="">
                        @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="Status">Status Buku</label>
                    <div class="col-md-10">
                        <div class="checkbox">
                            <input id="Status" name="Status" type="checkbox" placeholder="" class="checkbox" required="">
                        </div>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label">Upload Buku</label>
                    <div class="col-md-10">
                        <input id="ImageFile" name="ImageFile" type="file" onchange="show(this)" /> <br />
                        <img id="user_img" height="100" width="90" style="border: solid" src="/Images/@Model.Gambar" />
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-md-2 control-label" for="submit"></label>
                    <div class="col-md-10">
                        <button id="submit" name="submit" type="submit" class="btn btn-success">Save</button>
                    </div>
                </div>

                <div>
                    <a href="/Buku">Back to List</a>
                </div>

            </fieldset>

        </form>

    </div>

</div>

@section Scripts {
   @*@Scripts.Render("~/bundles/jqueryval")*@
    <script type="text/javascript">
        function show(input) {
            if (input.files && input.files[0]) {
                var filerdr = new FileReader();
                filerdr.onload = function (e) {
                    $('#user_img').attr('src', e.target.result);
                }
                filerdr.readAsDataURL(input.files[0]);
            }
        }
    </script>
}

Training/Views/Buku/IndexBukus.cshtml
<div class="container">
    <div class="row col-md-6 col-md-offset-2 accent-blue">
        <table class="table table-striped accent-dark">

            <a href="/Buku/TambahBuku"
               class="btn btn-success btn-sm pull-left">
                <b>+</b> Tambahkan Buku
            </a>

            <tr>
                <th> Judul Buku </th>
                <th> Nama Penulis </th>
                <th> Penerbit </th>
                <th> Status Buku </th>
                <th> Gambar </th>
                <th> Action </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td> @item.Judul </td>
                    <td> @item.Penulis </td>
                    <td> @item.Penerbit </td>
                    <td> @item.Status </td>
                    <td> <img style="width:58px;height:60px" src="@item.Gambar" /></td>
                    <td>
                        <a href="/Buku/DetailsBuku/@item.BukuId" class="btn"><i class="icon-pencil"></i> <strong> Details </strong></a> |
                        <a href="/Buku/EditBuku/@item.BukuId" class="btn"><i class="icon-edit"></i> <strong>Edit</strong></a> |
                        <a href="/Buku/DeleteBuku/@item.BukuId" class="btn"><i class="icon-trash"></i> <strong>Delete</strong></a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

Training/Views/Buku/TambahBuku.cshtml
@model Training.Core.Model.Buku

@{
    ViewBag.Title = "Tambah Buku";
}

<h2> Tambah Buku </h2>

<form action="/Buku/TambahBuku" enctype="multipart/form-data" method="post">
    @*@using (Html.BeginForm("Create", "Buku",
        FormMethod.Post, new { enctype = "multipart/form-data" }))*@
    <fieldset>
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Buku</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2">Judul Buku</label>
                @*@Html.LabelFor(model => model.Judul, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Judul, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Judul, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Nama Penulis</label>
                @*@Html.LabelFor(model => model.Penulis, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Penulis, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Penulis, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Nama Penerbit</label>
                @*@Html.LabelFor(model => model.Penerbit, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Penerbit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Penerbit, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Deskripsi</label>
                @*@Html.LabelFor(model => model.Deskripsi, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Deskripsi, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Deskripsi, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Kategori</label>
                @*@Html.LabelFor(model => model.KategoriId, "KategoriId", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.DropDownList("KategoriId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.KategoriId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Status Buku</label>
                @*@Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.Status)
                        @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2">Upload Buku</label>
                @*@Html.LabelFor(model => model.Gambar, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    <input type="file" name="ImageFile" id="ImageFile" onchange="show(this)" /> <br />
                    <img id="user_img" height="100" width="90" style="border:solid" />
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </fieldset>
</form>

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @*@Scripts.Render("~/bundles/jquryval")*@
    <script type="text/javascript">
        function show(input) {
            if (input.files && input.files[0]) {
                var filerdr = new FileReader();
                filerdr.onload = function (e) {
                    $('#user_img').attr('src', e.target.result);
                }
                filerdr.readAsDataURL(input.files[0]);
            }
        }
    </script>
}